services:
  remnawave-tg-shop-db:
    image: postgres:17
    container_name: remnawave-tg-shop-db
    hostname: remnawave-tg-shop-db
    env_file:
      - .env
    ports:
      - "5432:5432"  # Проброс порта для доступа с хоста
    volumes:
      - remnawave-tg-shop-db-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  remnawave-tg-shop-db-data:
    name: remnawave-tg-shop-db-data